[discrete]
= Forord [[forord]]

Dette dokumentet er utarbeidet av helsedataavdelingen i Folkehelseinstituttet FHI og
beskriver hvordan metadata fra sentrale helseregistre, nasjonale medisinske kvalitetsregistre og befolkningsbaserte helseundersøkelser skal eksporteres til Nasjonal variabelkatalog, samt hvordan metadata forvaltes i Nasjonal variabelkatalog. 

Målgruppen for dokumentet er dataforvaltere og tekniske utviklere i de nasjonale helsedatakildene. Spesifikasjonen setter føringer for hvordan helsedata til sekundære formål skal dokumenteres. Videre legger spesifikasjonen til rette for etableringen av en nasjonal Helseanalyseplattform ved å sikre at data som skal forvaltes på plattformen blir beskrevet på en lik måte og kan utveksles maskinelt. 

Spesifikasjonen bygger på arbeidet som ble igangsatt gjennom infrastrukturprosjektet Health Registries for Research der de sentrale helseregistrene etablerte en felles minimumsstandard for dokumentering av registervariabler [1]. Dette arbeidet ble videreført gjennom Helsedataprogrammet i Direktoratet for e-helse. Da ble minimumsstandarden videreutviklet til å inkludere dokumentering av metadata om både datakildene selv, tilhørende datasamlinger, versjoner og kodeverkene som anvendes. Senere ble spesifikasjonen utvidet til å kunne dokumentere metadata om medisinske kvalitetsregistre og befolkningsbaserte helseundersøkelser. 

Arbeidet har blitt forankret i tett dialog med berørte interessenter. 

Hovedbruksområder for metadata vil være i søknadsprosessen på helsedata.no og for eksport til den Europeiske helsedataportalen EHDS. 
Spesifikasjonen vil etter hvert revideres for å favne ytterligere behov relatert til utvikling av den Nasjonale variabelkatalogen og for å kunne favne metadata fra flere helsedatakilder som f.eks. biobanker, prøvesamlinger og biodata samt tverrsektorielle og internasjonale behov. 

Videre arbeid med begrepskoordinering på variabelnivå, bruk av kodeverk og utvikling av felles overordnede begreps- og/eller informasjonsmodeller vil foregå i nært samarbeid med registerforvaltere og relevante fagavdelinger i FHI og Helsedirektoratet. 

Spesifikasjonen utvikles i tråd med https://www.go-fair.org/fair-principles/[FAIR-prinsippene] og de internasjonale standardene https://data.norge.no/specification/dcat-ap-no[DCAT] og SKOS, og gjennom anbefalinger innhentet gjennom samarbeide i Europeiske og Nordiske prosjekter og arbeidsgrupper.
