= Innledning [[innledning]]

*1.1 Bakgrunn*

Arbeidet med å definere og innrapportere standardiserte metadata fra helseregistre ble initiert gjennom infrastrukturprosjektet Health Registries for Research (HRR) [1]. HRR ble avsluttet i 1. kvartal 2019 og Helsedataprogrammet i Direktoratet for e-helse videreførte dette arbeidet. Gjennom 2020 har spesifikasjonen blitt utvidet til å inkludere metadata fra nasjonale medisinske kvalitetsregistre og befolkingsbaserte helseundersøkelser. Nasjonal variabelkatalog ble etablert i løsningen HealthTerm i 2019. HealthTerm ble levert av CareCom AS og er anskaffet av Direktoratet for e-helse, Etableringen av variabelkatalogen er avgjørende for utviklingen av en god variabelutforsker på helsedata.no og inngår som en viktig komponent i utviklingen av en effektiv søknadstjeneste og Helseanalyseplattformen. Gjennom etableringen av data- og analysetjenester på Helseanalyseplattformen, vil det å overføre dataprodukter fra utvalgte datakilder til Helseanalyseplattformen stå sentralt. Gode metadata vil være avgjørende for at Helsedataservice skal kunne forvalte dataprodukter på Helseanalyseplattformen. Videre vil datamodellen for metadata danne grunnlaget for å spesifisere dataprodukter som skal overføres til Helseanalyseplattformen. Selve dataoverføringen er nærmere forklart i Spesifikasjon til dataoverføring til Helseanalyseplattformen1.

Behovet for metadata om helsedatakilder og deres innhold (variabler), er tydelig forankret i Nasjonal e-helsestrategi 2017-2022 [2].

*1.2 Formål*

Spesifikasjonen skal bidra til å sikre at metadata om helsedatakilder dokumenteres og tilgjengeliggjøres på en standardisert og strukturert måte slik at de kan forståes og utveksles mellom aktører og systemer, også på tvers av landegrenser. Spesifikasjonen er tiltenkt å dekke informasjonsbehovet for bruk av data til sekundære formål som forskning, kvalitetsforbedring og annen analyse. Spesifikasjonen legger derfor føringer på hvilken informasjon som det er obligatorisk å innrapportere, hvilken som er anbefalt og hvilken som er valgfri. Metadata vil utveksles med helsedata.no for å understøtte søknadsprosessen i et felles søknadsskjema. Innrapportering av metadata vil også være en forutsetning for overføring av data til Helseanalyseplattformen. Helseanalyseplattformen validerer dataene på plattformen opp mot metadataene og koblingen mellom data og metadata er avgjørende for at dataene skal være forståelige ved utlevering. Metadata vil også utveksles med andre metadatakataloger som f.eks. Felles datakatalog og data.europa.eu, noe som krever en gradvis tilpasning til internasjonale standarder for utveksling og deling av metadata.

1 Spesifikasjon for dataoverføring til Helseanalyseplattformen er p.t. en prosjektleveranse fra Helsedataprogrammet i forbindelse med utviklingen av Helseanalyseplattformen og deles på forespørsel. Spesifikasjonen skal ila 2021 videreutvikles og etableres som en normerende retningslinje på linje med Nasjonal spesifikasjon for metadata om helsedata.

Nasjonal spesifikasjon for metadata om helsedata
8
Det er gjort flere utvidelser av metadatamodellen fra versjon 1.0 til versjon 1.1 av spesifikasjonen. Dette er gjort for å kunne beskrive datakilder som medisinske kvalitetsregistre og befolkningsbaserte helseundersøkelser på en mer presis måte, samt å gi mer relevant informasjon til brukerne av dataene. Enkelte av klassene i modellen er frivillig å ta i bruk. Videre har flere properties som var satt som valgfrie i forrige versjon blitt gjort om til obligatoriske eller anbefalte i denne. Dette er gjort ut fra en vurdering av hvilken informasjon som vil være mest nyttig for brukere av helsedataene, samt etter tilbakemeldinger fra forvaltere av de aktuelle helsedatakildene.

*1.3 Omfang og avgrensninger*

Dette dokumentet er utformet som en spesifikasjon. Etter hvert som spesifikasjonen blir implementert, metadata fra nye datakilder blir importert og nye erfaringer gjøres, er målet at spesifikasjonen får status som en anbefalt standard. Dette er en lengre prosess og avhenger av god forankring i sektoren og utviklingen av rammeverk for tverrsektorielt og internasjonalt samarbeide. Spesifikasjonen omfatter foreløpig sentrale helseregistre, nasjonale medisinske kvalitetsregistre og befolkningsbaserte helseundersøkelser. Fremtidige versjoner av spesifikasjonen vil også kunne stille krav til innrapportering av metadata fra andre helsedatakilder som f.eks. biodata og gendata. Spesifikasjonen må i så fall utvides til også å stille krav om hvordan denne typen data skal dokumenteres. Etter hvert vil sannsynligvis en god del metadata kunne bli generert og hentet fra primærkilder som f.eks. PAS/EPJ, labsystemer og radiologisystemer , medisinsk teknisk utstyr og personlige applikasjoner. Hvor og hvordan dette skal spesifiseres, og hvordan dette vil påvirke sektoren og systemleverandører, vil bli vurdert når den tid kommer. Spesifikasjonen gir ikke føringer for hvordan metadata skal struktureres og forvaltes i lokale løsninger hos den enkelte dataforvalter, kun for hvordan dette skal innrapporteres til den nasjonal variabelkatalog. Denne versjonen av spesifikasjonen støtter ikke automatisert overføring av metadata til den nasjonale variabelkatalogen, og det legges derfor opp til at metadata skal overføres via epost, se 4.1.1. Dette er ikke en skalerbar løsning, og Direktoratet for e-helse har derfor til hensikt å sende på høring en oppdatert spesifikasjon i løpet av 2022 der det legges til rette for å automatisere overføring av metadata til nasjonal variabelkatalog ved bruk av API. Beskrivelsene av metadataene er i stor grad basert på de internasjonale standardene DCAT [3] og SKOS [4], og Digitaliseringsdirektoratets norske versjoner av disse [5] [6], noe som gjør det langt enklere å dele og validere kvaliteten på metadata på tvers av sektorer og landegrenser. Et forslag til mapping mellom properties fra Nasjonal spesifikasjon for metadata om helsedata (dette dokumentet) og de nevnte standardene finnes i Vedlegg 1 og Vedlegg 2. Spesifikasjonen forvaltes og videreutvikles i henhold til Veileder for bruk av FAIR-prinsippene for helsedatakilder [7].
