= Innledning [[innledning]]

== Bakgrunn

Arbeidet med å definere og innrapportere standardiserte metadata fra helseregistre ble initiert gjennom infrastrukturprosjektet Health Registries for Research (HRR) [1]. HRR ble avsluttet i 1. kvartal 2019 og Helsedataprogrammet i Direktoratet for e-helse videreførte dette arbeidet. Gjennom 2020 ble spesifikasjonen utvidet til å inkludere metadata fra nasjonale medisinske kvalitetsregistre og befolkingsbaserte helseundersøkelser. 
Nasjonal variabelkatalog ble etablert i løsningen HealthTerm i 2019. HealthTerm er levert av Rhapsody, tidligere CareCom AS og er anskaffet av Helsedirektoratet.
Etableringen av variabelkatalogen er avgjørende for utviklingen av en god variabelutforsker på helsedata.no og inngår som en viktig komponent i utviklingen av en effektiv søknadstjeneste. 

Behovet for metadata om helsedatakilder og deres innhold (variabler), er tydelig forankret i Nasjonal e-helsestrategi 2017-2022 [2], og 2023-2030 [3]

*1.2 Formål*

Spesifikasjonen skal bidra til å sikre at metadata om helsedatakilder dokumenteres og tilgjengeliggjøres på en standardisert og strukturert måte slik at de kan forståes og utveksles mellom aktører og systemer, også på tvers av landegrenser. Spesifikasjonen er tiltenkt å dekke informasjonsbehovet for bruk av data til sekundære formål som forskning, kvalitetsforbedring og annen analyse. Spesifikasjonen legger derfor føringer på hvilken informasjon som det er obligatorisk å innrapportere, hvilken som er anbefalt og hvilken som er valgfri. Metadata vil utveksles med helsedata.no for å understøtte søknadsprosessen i et felles søknadsskjema.  Metadata vil også utveksles med andre metadatakataloger som f.eks. Felles datakatalog og HealthData@EU, noe som krever en gradvis tilpasning til internasjonale standarder for utveksling og deling av metadata.


*1.3 Omfang og avgrensninger*

Dette dokumentet er utformet som en spesifikasjon. Etter hvert som spesifikasjonen blir implementert, metadata fra nye datakilder blir importert og nye erfaringer gjøres, er målet at spesifikasjonen får status som en anbefalt standard. Dette er en lengre prosess og avhenger av god forankring i sektoren og utviklingen av rammeverk for tverrsektorielt og internasjonalt samarbeide. Spesifikasjonen omfatter foreløpig sentrale helseregistre, nasjonale medisinske kvalitetsregistre og befolkningsbaserte helseundersøkelser. Fremtidige versjoner av spesifikasjonen vil også kunne stille krav til innrapportering av metadata fra andre helsedatakilder som f.eks. prøvesamlinger og biodata. Spesifikasjonen må i så fall utvides til også å stille krav om hvordan denne typen data skal dokumenteres. Etter hvert vil sannsynligvis en god del metadata kunne bli generert og hentet fra primærkilder som f.eks. PAS/EPJ, labsystemer og radiologisystemer , medisinsk teknisk utstyr og personlige applikasjoner. Hvor og hvordan dette skal spesifiseres, og hvordan dette vil påvirke sektoren og systemleverandører, vil bli vurdert når den tid kommer. Spesifikasjonen gir ikke føringer for hvordan metadata skal struktureres og forvaltes i lokale løsninger hos den enkelte dataforvalter, kun for hvordan dette skal innrapporteres til den nasjonal variabelkatalog. Denne versjonen av spesifikasjonen støtter ikke automatisert overføring av metadata til den nasjonale variabelkatalogen, og det legges derfor opp til at metadata skal overføres via epost, se 4.1.1. Dette er ikke en skalerbar løsning, og FHI det vurderes ulike alternativ for på sikt å automatisere overføring av metadata til nasjonal variabelkatalog ved bruk av API. Beskrivelsene av metadataene er i stor grad basert på de internasjonale standardene DCAT [4] og SKOS [5], og Digitaliseringsdirektoratets norske versjoner av disse [6] [7], noe som gjør det langt enklere å dele og validere kvaliteten på metadata på tvers av sektorer og landegrenser. Et forslag til mapping mellom properties fra Nasjonal spesifikasjon for metadata om helsedata (dette dokumentet) og de nevnte standardene finnes i Vedlegg 1 og Vedlegg 2. Spesifikasjonen forvaltes og videreutvikles i henhold til Veileder for bruk av FAIR-prinsippene for helsedatakilder [8].
