= Innledning [[innledning]]

*1.1 Background

The work on defining and reporting standardised metadata from health registries was initiated through the Health Registries for Research (HRR) infrastructure project [1]. HRR was concluded in the first quarter of 2019, and the Health Data Programme in the Norwegian Directorate of eHealth continued this work. Throughout 2020, the specification has been expanded to include metadata from national medical quality registers and population-based health surveys. The national variable catalogue was established in the HealthTerm solution in 2019. HealthTerm was delivered by CareCom AS and was procured by the Norwegian Directorate of eHealth. The establishment of the variable catalogue is crucial for the development of a good variable explorer on helsedata.no and is an important component in the development of an efficient application service and the Health Analysis Platform. Through the establishment of data and analysis services on the Health Analysis Platform, the transfer of data products from selected data sources to the Health Analysis Platform will be central. Good metadata will be crucial for Helsedataservice to be able to manage data products on the Health Analytics Platform. Furthermore, the data model for metadata will form the basis for specifying data products to be transferred to the Health Analytics Platform. The actual data transfer is explained in more detail in the Specification for data transfer to the Health Analytics Platform1.

The need for metadata about health data sources and their content (variables) is clearly anchored in the National eHealth Strategy 2017-2022 [2].

*1.2 Purpose

The specification shall help to ensure that metadata about health data sources are documented and made available in a standardised and structured manner so that they can be understood and exchanged between actors and systems, including across national borders. The specification is intended to cover the information needs for the use of data for secondary purposes such as research, quality improvement and other analyses. The specification therefore provides guidelines on which information is mandatory to report, which is recommended and which is optional. Metadata will be exchanged with helsedata.no to support the application process in a common application form. Reporting of metadata will also be a prerequisite for transferring data to the Health Analytics Platform. The Health Analytics Platform validates the data on the platform against the metadata, and the link between data and metadata is crucial for the data to be understandable upon delivery. Metadata will also be exchanged with other metadata catalogues such as the Common Data Catalogue and data.europa.eu, which requires a gradual adaptation to international standards for exchanging and sharing metadata.

1 The specification for data transfer to the Health Analytics Platform is currently a project delivery from the Health Data Programme in connection with the development of the Health Analytics Platform and is shared on request. In 2021, the specification will be further developed and established as a normative guideline in line with the National specification for metadata about health data.

National specification for metadata about health data
8
Several extensions have been made to the metadata model from version 1.0 to version 1.1 of the specification. This has been done in order to describe data sources such as medical quality registers and population-based health surveys in a more precise way, as well as to provide more relevant information to the users of the data. Some of the classes in the model are optional to use. Furthermore, several properties that were set as optional in the previous version have been changed to mandatory or recommended in this version. This has been done based on an assessment of what information will be most useful for users of the health data, as well as on feedback from managers of the relevant health data sources.

*1.3 Scope and limitations

This document is designed as a specification. As the specification is implemented, metadata from new data sources is imported and new experiences are gained, the goal is for the specification to achieve the status of a recommended standard. This is a longer process and depends on good anchoring in the sector and the development of a framework for cross-sectoral and international co-operation. The specification currently covers central health registers, national medical quality registers and population-based health surveys. Future versions of the specification may also require the reporting of metadata from other health data sources such as biodata and gene data. In that case, the specification must be expanded to include requirements for how this type of data should be documented. Eventually, a good deal of metadata will probably be generated and retrieved from primary sources such as PAS/EPJ, lab systems and radiology systems, medical technical equipment and personal applications. Where and how this will be specified, and how this will affect the sector and system suppliers, will be considered in due course. The specification does not provide guidelines for how metadata should be structured and managed in local solutions at the individual data manager, only for how this should be reported to the national variable catalogue. This version of the specification does not support automated transfer of metadata to the national variable catalogue, and it is therefore proposed that metadata should be transferred via email, see 4.1.1. This is not a scalable solution, and the Directorate of eHealth therefore intends to submit an updated specification for consultation in 2022, which will facilitate automated transfer of metadata to the national variable catalogue using an API. The descriptions of the metadata are largely based on the international standards DCAT [3] and SKOS [4], and the Norwegian Digitalisation Directorate's Norwegian versions of these [5] [6], which makes it far easier to share and validate the quality of metadata across sectors and national borders. A proposal for mapping between properties from the National specification for metadata on health data (this document) and the aforementioned standards can be found in Appendix 1 and Appendix 2. The specification is managed and further developed in accordance with the Guidelines for the use of the FAIR principles for health data sources [7].


